### ISSUE TITLE
Login Issue => TwoFactor auth

### ISSUE THREAD

**Issue by racdamico** [liberavia/geforcenow#1]
When I try to login with my Gmail account in to NVIDIA, after insert the 2 step (authenticator token), I got an error of login unsuccessful.

**Comment by jomal1** [comment]
same

**Comment by xVANKO** [comment]
i confirm this issue

**Comment by bickkysahani** [comment]
same here

**Comment by liberavia** [comment]
Sorry for reacting so late. With the latest release I am able to pass 2FA. Is this issue solved by this release for you?

**Comment by bickkysahani** [comment]
yes, thank you for the latest update. it solved my issue.

**Comment by liberavia** [comment]
I just closed this one. Also related white-page-after-login problem is solved by release 0.3.5. Thank you very much for reporting and giving attention. Promise to respond faster next time.  I was able to play without a hassle using a ps4-controller on the latest release.
