### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by bickkysahani** [liberavia/geforcenow#2]
Login fails

**Comment by bernardodpc** [comment]
I can confirm. login always fails. 
at first I couldn't pass the home page because of https://github.com/liberavia/geforcenow/issues/4
but now I can reach login screen; but can't continue...

**Comment by liberavia** [comment]
Currently Login is also not working for me either. It ends up in a white page for me. Is this the behaviour you enounter too or is it different? (Related to latest release 0.3.4)

**Comment by bernardodpc** [comment]
> Currently Login is also not working for me either. It ends up in a white page for me. Is this the behaviour you enounter too or is it different? (Related to latest release 0.3.4)

yes, I get the same white screen (and a message telling me the login failed on background) when I try to login via email.

edit: now I think I am experiencing the same behavior as yours. I get only a white screen after trying to login with email and password. no more messages on background saying my login failed.

**Comment by liberavia** [comment]
Thanks a lot for your report. Version 0.3.5 solves the issue, which was related to a feature need to be set in Electron > 15.x . I was now able to play with my ps4-controller after a snap refresh.
